---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: moonlightos
version: 1
description: MoonlightOS image based on Bazzite Nvidia.
base-image: ghcr.io/ublue-os/bazzite-nvidia-open
image-version: latest

platforms:
  - linux/amd64

labels:
  org.opencontainers.image.title: MoonlightOS
  org.opencontainers.image.description: Gaming-focused atomic Linux image based on Bazzite Nvidia.
  org.opencontainers.image.licenses: MIT

modules:
  - from-file: modules/foundation.yml
